// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://al6qkw4epzewtn7jxdqwu6wdle.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z4w26fzytrherfuor4f6kztze4",
    "aws_cognito_identity_pool_id": "us-east-1:7a780aa7-6568-482f-9b75-81d2b3599ffa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dvjFTXvgM",
    "aws_user_pools_web_client_id": "4pdq3ia52q5466ah3s2jd0a5m9",
    "oauth": {},
    "aws_mobile_analytics_app_id": "912c48361859497691546acdcbee2068",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "ampapp-20190607104308-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://ampapp-20190607104308-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
